name: Build and Deploy

on: push

env:
  applicationfolder: spring-boot-hello-world-example
  AWS_REGION: ap-northeast-2
  S3BUCKET: cide-codedeploy-4878
  PROJECT_NAME: cicdproject
  CODE_DEPLOY_APP_NAME: cicdapp
  DEPLOYMENT_GROUP_NAME: cicdapp_deploy
  EC2_INSTANCE_ID: i-0b365d187cba76b60


jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repository

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: chmod
        run: chmod -R +x ./.github

      - name: Build and Package Maven
        id: package
        working-directory: ${{ env.applicationfolder }}
        run: $GITHUB_WORKSPACE/.github/scripts/build.sh

      - name: Upload Artifact to s3
        working-directory: ${{ env.applicationfolder }}/target
        run: aws s3 cp *.war s3://${{ env.S3BUCKET }}/
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: Dev
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Install Tomcat on EC2
      run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceIds,Values=${{ env.EC2_INSTANCE_ID }}" \
            --parameters 'commands=[
              "sudo yum update -y",
              "sudo amazon-linux-extras enable tomcat10",
              "sudo yum install -y tomcat",
              "sudo systemctl enable tomcat",
              "sudo systemctl start tomcat",
              "sudo systemctl status tomcat"
            ]' \
            --region ${{ secrets.AWS_REGION }}
    - run: |
        echo "Deploying branch"
        commit_hash=`git rev-parse HEAD`
        aws deploy create-deployment --application-name $CODE_DEPLOY_APP_NAME \
        --deployment-group-name $DEPLOYMENT_GROUP_NAME \
        --github-location repository=$GITHUB_REPOSITORY,commitId=$commit_hash \
        --ignore-application-stop-failures
